app/controllers/unaccompanied_controller.rb, app/views/unaccompanied-minor/guidance.html.erb, app/views/unaccompanied-minor/start.html.erb, config/routes.rb, spec/system/unaccompanied_minor_spec.rb
[Jira ticket](https://digital.dclg.gov.uk/jira/projects/UKRSS/issues/UKRSS-503)
What's missing:
=> Add guidance page and new start flow to unaccompanied minor

app/views/sponsor-a-child/steps/18.html.erb, app/views/sponsor-a-child/steps/29.html.erb, app/views/sponsor-a-child/steps/34.html.erb
Just moving the headers inside the form and then the error summary above the headers in accordance with GDS
=> moving error summary up to top of page for DoB errors

app/controllers/unaccompanied_controller.rb, app/views/sponsor-a-child/steps/22.html.erb, config/routes.rb, spec/system/unaccompanied_minor_sponsor_other_nationalities_spec.rb
This pr covers adding remove option for sponsors other **nationalities** in [Jira ticket 783](https://digital.dclg.gov.uk/jira/browse/UKRSS-783)
* Remove link added
* Layout is consistent with residents page
=> Enable remove option for sponsor other nationalities

app/controllers/foundry_consent_upload_controller.rb, app/jobs/send_unaccompanied_minor_job.rb, app/use-cases/transfer_consents.rb, app/use-cases/transfer_record.rb, spec/controllers/use-cases/transfer_consents_spec.rb
- Added a "safe" deletion of downloaded tmp files 
- Extracted a class TransferConsents, from TransferRecord, and test directly
- Cleans `transfer record` "job" class to a standard pattern
=> 500 Upload consents - delete tmp files

app/models/concerns/uam_validations.rb, spec/controllers/unaccompanied_controller_spec.rb, spec/models/concerns/uam_validations_spec.rb, spec/system/unaccompanied_minor_spec.rb
[JIRA# 839](https://digital.dclg.gov.uk/jira/browse/UKRSS-839)
- Validates other sponsor residential address and blocks entry with invalid values.
- Highlights fields as required
=> 839 - Sponsor residential address validation

app/controllers/unaccompanied_controller.rb, app/models/concerns/additional_info_validations.rb, app/models/concerns/common_validations.rb, app/models/concerns/contact_details_validations.rb, app/models/concerns/uam_validations.rb, app/views/sponsor-a-child/steps/12.html.erb, spec/models/concerns/common_validations_spec.rb
[Jira 878](https://digital.dclg.gov.uk/jira/browse/UKRSS-878)
Given name and family name validations were:
- Permitting '+' and '~' chars
- Not consistently applied across all names
This PR creates a single reusable validator and points all names to the validator.
- Min length of 1 char
- Permit space, hyphen and apos
- No special chars
=> 878 - Fix name validation

app/controllers/unaccompanied_controller.rb, app/models/concerns/uam_validations.rb, spec/controllers/unaccompanied_controller_spec.rb
To hit a release deadline we were deleting validation errors on final submission.
Time to pay that debt down and scratch that dirty itch 💪🏻
The errors were for fields:
-  That are not submitted in the json
-  Used as "proxy" data placeholders, in the views (see [27.html.erb](app/views/sponsor-a-child/steps/27.html.erb)) for other the "others adults" data.
- Unwinding it completely is likely too much at this point in time 
This PR simply disables the relevant validators.
Now I feel better!
=> Delete tech-debt to swerve validators incorrectly running on submit 👊🏻 

app/controllers/token_based_resume_controller.rb, app/views/token-based-resume/select_multiple_applications.erb, config/routes.rb, spec/controllers/token_based_resume_controller_spec.rb, spec/system/token_based_resume_controller_spec.rb
Branched from #251 (needs to be in master before this can be merged)
Jira ticket: https://digital.dclg.gov.uk/jira/browse/UKRSS-854
=> Save and return multiple applications

app/controllers/token_based_resume_controller.rb, app/views/token-based-resume/select_multiple_applications.erb, config/routes.rb, spec/controllers/token_based_resume_controller_spec.rb
This is just to avoid exposing the `reference` of an application in the url bar, plus it's csrf-protected
=> Converts selecting an application to resume from GET to POST

app/controllers/errors_controller.rb
Our top error is not gracefully handling 404's that come from googlebot.
This will simply return an empty "text/plain" and empty 404 and reduce template not found errors.
See [here](https://www.dxw.com/2014/05/rendering-nothing-on-404-in-a-ruby-on-rails-api/) for the reasoning.
=> Render empty 404 for (googlebot) requests that are not html.

app/mailers/gov_notify_mailer.rb
[Jira 906](https://digital.dclg.gov.uk/jira/browse/UKRSS-906)
By design gov.notify will not send emails to non team members in non prod envs and raises an exception.
This is expected behaviour that pollutes the error logs - we trap and ignore them
=> Trap and ignore expected gov notify errors in no prod

config/initializers/sentry.rb
The Sentry logging volume was exceeded last month.
This PR will stop logs for the health end point - we don't need to know the performance and it was the largest volume.
=> Stop sentry logging for health end point

app/views/sponsor-a-child/check_answers.html.erb
[JIRA-912](https://digital.dclg.gov.uk/jira/browse/UKRSS-912)
The child contact details "type" is now an array because multiple entries are possible.
This breaks the check answers page.
This is not tested so regressed in https://github.com/communitiesuk/ukraine-sponsor-resettlement/pull/257
Regression tests to follow!
=> 912 - Quick fix for check answers - child contact details

Gemfile.lock, app/controllers/unaccompanied_controller.rb, config/locales/en.yml, spec/system/unaccompanied_minor_minors_details_spec.rb, spec/system/unaccompanied_minor_spec.rb
[JIRA-902](https://digital.dclg.gov.uk/jira/browse/UKRSS-902)
Used to show no error on Child DoB in future. This has been fixed as shown below.
=> 902 future date on child dob

Gemfile.lock, app/views/sponsor-a-child/steps/29.html.erb, spec/system/sponsor_additional_details_spec.rb, spec/system/unaccompanied_minor_other_adults_spec.rb
[Jira-913](https://digital.dclg.gov.uk/jira/browse/UKRSS-913)
All DoBs now retain the information in their fields when pages are reloaded.
=> Retain child dob

app/views/sponsor-a-child/start.html.erb
Shows the caret in Start now button
Found the solution in https://govuk-components.netlify.app/components/start-button/#input-erb-start-button
Fixes https://digital.dclg.gov.uk/jira/browse/UKRSS-908
=> Fix start now as per GDS

.github/workflows/deploy-pipeline.yml, app/controllers/foundry_consent_upload_controller.rb
[JIRA-933](https://digital.dclg.gov.uk/jira/browse/UKRSS-933)
In **all envs except test** - secures consent uploader "admin" form behind basic auth using new env var pair.
Env vars are set and ready to go and entered into the password store.
=> 933 add http basic auth security to consent upload form

app/helpers/application_helper.rb
Jira ticket https://digital.dclg.gov.uk/jira/browse/UKRSS-905
I found out that this was because of how the government provided list is configured
Each nationality has 2 items: country code and country name.
The country code does not correspond to the country name all the times: example, Southern French Territories has ATF as the country code.
The default ordering places it at the top with the As, rather than towards the bottom with the Ss.
I have fixed it by making it sort by country name instead
=> Sort nationalities by name

app/controllers/unaccompanied_controller.rb, spec/controllers/unaccompanied_controller_spec.rb
Our top sentry error (41 times) is when a user somehow `get`s to a step and the application is not found.
This PR traps the fault and redirects to the start page.
**Note** we were already trapping step out of range. An explicit test has been added for this.
EG: Try in a "clean" incognito window this link: [Step 1](https://apply-to-offer-homes-for-ukraine.service.gov.uk/sponsor-a-child/steps/1) - a terrible experience 😞
- **Currently**
- **New Behaviour**
=> Trap 500's when application not found and redirect to start page

app/views/sponsor-a-child/guidance.html.erb, app/views/sponsor-a-child/non_eligible.html.erb, app/views/sponsor-a-child/steps/35.html.erb, app/views/sponsor-a-child/steps/36.html.erb, app/views/sponsor-a-child/steps/37.html.erb
I only searched the following subfolders: `sponsor-a-child` and `fraud`, not the `organisation` or `individual` views for I don't think they're in scope for this ticket
=> Add target=_blank to all the external links missing it

.github/workflows/deploy-pipeline.yml
Following a live sidekiq issue, these env vars are required in sidekiq due to their placement, and fetch call, in the FoundryConsentUploadController
The fix was achieved via the cf command line - this PR ensures they are in the pipeline.
Github vars have also been checked / configured.
=> Add consent uploader ENV var credentials to sidekiq

app/views/sponsor-a-child/steps/14.html.erb, app/views/sponsor-a-child/steps/15.html.erb, config/locales/en.yml, spec/system/confirm_page_spec.rb, spec/system/token_based_resume_controller_spec.rb, spec/system/unaccompanied_minor_spec.rb
PR 1005[https://digital.dclg.gov.uk/jira/browse/UKRSS-1005](url)
Updating email and phone number input fields to have labels instead of hints.  Updated tests
=> updating email input fields to have labels

app/views/sponsor-a-child/steps/36.html.erb
PR for 1016 [1016](https://digital.dclg.gov.uk/jira/browse/UKRSS-1016)
Updating the hint text to be a hint instead of body text .
Re text "You will need to upload the 'Ukrainian certified consent form' on the next page."
Before 
After
=> update the hint text field to be a hint

app/views/sponsor-a-child/steps/6.html.erb, app/views/sponsor-a-child/steps/7.html.erb
PR for ticket [1039](https://digital.dclg.gov.uk/jira/browse/UKRSS-1039). Moved the text from step 6 into a detail component and moved details component on step 7 to above the radio buttons. 
Old views:
New views:
=> 1039 move minimum period to details

app/controllers/unaccompanied_controller.rb, app/models/concerns/common_validations.rb, config/locales/en.yml, spec/system/sponsor_additional_details_spec.rb, spec/system/uam_sponsor_contact_details_spec.rb, spec/system/unaccompanied_minor_spec.rb
PR for ticket [1035](https://digital.dclg.gov.uk/jira/browse/UKRSS-1035)
Adds validation for sponsor Identity document other page. If the field is blank it won't let the user continue. 
Old view: 
New view:
=> 1035 validation for identity question

app/models/concerns/unaccompanied_minor_transfer_adapter.rb, spec/support/json_schema/unaccompanied_minor.json, spec/support/unaccompanied_minor_helpers.rb, spec/system/confirm_page_spec.rb, spec/system/unaccompanied_minor_spec.rb
**Second pr** for [Jira ticket 991](https://digital.dclg.gov.uk/jira/browse/UKRSS-991)
This PR adds the functionality for the adapter to output Sponsor, Section one, optional additional details:
- other_names
- no_identification_reason
- other_nationalities
**To follow**
- Section 2 optional entries
- Section 3 optional entries
=> 991 - Add schema and output for Sponsor, Section 1 additional details

app/views/sponsor-a-child/steps/30.html.erb
PR [1071](https://digital.dclg.gov.uk/jira/browse/UKRSS-1071?filter=-1)
Step 30 is missing a label for the text box and the inset text for the Other Adult Name is a hint text on the box meaning the error line extends into it.
Before
After
=> moving the inset to be an inset and correct label added

app/controllers/token_based_resume_controller.rb, docker-compose.yml, spec/system/token_based_resume_controller_spec.rb
[UKRSS-1009] (https://digital.dclg.gov.uk/jira/browse/UKRSS-1009)
From Sentry errors: https://sentry.io/share/issue/f9ae20faf39341b99424465e827bd6e4/
Removes serialization of UAM data to session.
Adds test for form data restoration when resuming application.
=>  1009: fix cookie overflow  

app/controllers/token_based_resume_controller.rb, spec/system/token_based_resume_controller_spec.rb
PR for [Jira-1076](https://digital.dclg.gov.uk/jira/browse/UKRSS-1076)
Added guard clause to token based resume for if no application present and save and return is visited. Should fix sentry error https://sentry.io/organizations/dluhc-ulss/issues/3644538887/?environment=production&project=6260319
Now redirects to "sponsor-a-child/start"
=> 1076 Token based resume no application present 

.github/workflows/deploy-pipeline.yml
Github actions pipeline has started (11th October) to emit warnings.
There appear to be 2 actions causing these:
1. `actions/checkout@v2`, **this PR** covers upgrading to `v3` and significantly reduces the warnings.
1. `ruby/setup-ruby@v1` - on [checking](https://github.com/ruby/setup-ruby) we are using the latest version. I suggest we wait a little while before deciding on further action. I suspect it will get updated as it is managed by the `ruby` org.
=> upgrade actions/checkout@v2 => v3

app/controllers/token_based_resume_controller.rb, spec/system/token_based_resume_controller_spec.rb
Redirects to start page if application isn't found on resume application page
=> adds guard clause for token based controller display method 

app/views/sponsor-a-child/steps/24.html.erb
PR for [JIRA-1079](https://digital.dclg.gov.uk/jira/browse/UKRSS-1079
Moved radio buttons on step 24 from inline to vertical.
Old view: 
New view:
=> Radio button layout fix

app/controllers/eoi_controller.rb, app/jobs/send_eoi_update_job.rb
Error in the logs
```
2022-10-19T14:31:50.79+0100 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/3.1.0/gems/zeitwerk-2.6.1/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /home/vcap/app/app/jobs/send_eoi_update_job.rb to define constant SendEoiUpdateJob, but didn't (Zeitwerk::NameError)
2022-10-19T14:31:50.79+0100 [APP/PROC/WEB/0] ERR raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)
2022-10-19T14:31:50.79+0100 [APP/PROC/WEB/0] ERR ^^^^^
2022-10-19T14:31:50.79+0100 [APP/PROC/WEB/0] ERR from /home/vcap/deps/0/vendor_bundle/ruby/3.1.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:28:in `require'
2022-10-19T14:31:50.79+0100 [APP/PROC/WEB/0] ERR from …
```
=> Fixes a naming error that causes deployment issues

app/controllers/eoi_controller.rb, app/views/eoi/check_answers.html.erb
Fixed check answers page shows incorrect answer to user research (actually showed answer to agree privacy)
Fixed check answers page is too intolerant of missing data (now shows empty fields instead of crashing)
Fixed check answers page missing capitalization of some Yes/No responses
https://digital.dclg.gov.uk/jira/browse/UKRSS-1159
=> 1159: Fix check answers page issues

app/controllers/application_controller.rb
Changing the GA path name to be included on the expression-of-interest path as opposed the deprecated individual path
=> correcting path name for google analytics

app/controllers/eoi_controller.rb
Adding validation for step 9 - if there is no option selected on the initial radio boxes and you press continue it will ask you to select an option.
=> adding validation for no option step 9

app/controllers/application_controller.rb, app/views/shared/_cookie_banner.html.erb
Had a regression error caused when the user had accepted or rejected cookies but not hidden the form.  Caused a 404 error which is now fixed.
=> fixing regression issues caused by querystring

app/views/eoi/steps/15.html.erb, app/views/eoi/steps/4.html.erb, app/views/eoi/steps/6.html.erb
PR for [Jira-1191](https://digital.dclg.gov.uk/jira/browse/UKRSS-1191) 
Moves summary error boxes to above the header
=> moves summary boxes to above header

app/javascript/packs/self_assessment_navigation.js, app/views/eoi/steps/can_you_commit.html.erb, app/views/eoi/steps/challenges.html.erb, app/views/eoi/steps/is_your_property_suitable.html.erb
PR [https://digital.dclg.gov.uk/jira/browse/UKRSS-1214](1214)
Adding error summary boxes to the self assessment user flow.   Summary boxes go above H1 and on all self assessment boxes where the user needs to select an option.
Works by toggling display setting to display block.
Before
After
=> adding error summary boxes to self assessment flow

policy.json, web-manifest.yml, worker-manifest.yml
https://digital.dclg.gov.uk/jira/browse/UKRSS-1667
09:45 Stéphane Meny
Hi all :wave::skin-tone-3: Lee ask me to do a quick estimation of how much an AWS equivalent of what is on PaaS (for HfU EOI form) would cost. I noticed we still run the main web server on 8 instances and 4 sidekiq instances. Do we still need that much compute power?
(based on the historical usage on Grafana we could determine if the utilisation is appropriate, not sure I still have access to the dashboard I still do so checking) (edited)
Except for a quick memory spike on an instance, it is clear the resources are under utilised, we could divide the resources by half.
=> lower to 4 web and 2 sidekiq instances

app/views/eoi/steps/different_address.html.erb, app/views/eoi/steps/more_properties.html.erb, app/views/eoi/steps/user_research.html.erb, app/views/sponsor-a-child/steps/1.html.erb, app/views/sponsor-a-child/steps/2.html.erb, app/views/sponsor-a-child/steps/24.html.erb, app/views/sponsor-a-child/steps/25.html.erb, app/views/sponsor-a-child/steps/3.html.erb, app/views/sponsor-a-child/steps/4.html.erb, app/views/sponsor-a-child/steps/5.html.erb, app/views/sponsor-a-child/steps/6.html.erb, app/views/sponsor-a-child/steps/7.html.erb, config/locales/en.yml
Turns out we had a problem in `locales/en.yaml` and we completely missed this commented bit
```
#
```
I've now properly scoped the yes/no answers to their respective questions, except for a couple of places where I used the `yes_no_types` as a fallback. A lot of duplicated yes/no I get it, but it's a bit more clear like this I think.
=> [accessibility fixes] DAC NON DESCRIPTIVE LABEL 01 for UAM and EOI

app/views/sponsor-a-child/steps/1.html.erb, app/views/sponsor-a-child/steps/11.html.erb, app/views/sponsor-a-child/steps/20.html.erb, app/views/sponsor-a-child/steps/25.html.erb, app/views/sponsor-a-child/steps/35.html.erb, app/views/sponsor-a-child/steps/6.html.erb, app/views/sponsor-a-child/steps/7.html.erb
We cannot get rid of the label using govuk's formbuilder, and the default for a label is `name_of_field` so I have modified the suggested solution to ensure there is a hidden text that states what the continue button is for
This also fixes https://digital.dclg.gov.uk/jira/browse/UKRSS-1832 due to a commit mistake on my end
=> [accessibility fixes] DAC_Non-Descriptive_Label_02

.github/workflows/deploy-aws-staging.yml, .gitignore, Dockerfile, Gemfile, Gemfile.lock, config/initializers/clamby.rb, config/initializers/ratonvirus.rb, docker-compose.yml
This PR configures ratonvirus to scan uploaded consent forms with ClamAV via clamby, rather than with just scanning for the EICAR test file.
It is to be deployed after deploying https://github.com/communitiesuk/ukraine-sponsor-terraform-scripts/pull/148, which creates the container in AWS
=> Clamav consent form scanning

.github/workflows/deploy-aws-staging.yml
This is preventing us from deploying updates while other updates are outstanding
=> Make "audit dependencies" step optional for deploying to AWS
