communitiesuk/ukraine-sponsor-resettlement

- Gemfile
- Gemfile.lock
> Bump Puma to something modern

- package.json
- yarn.lock
Update old dependency, should help resolve dependabot warnings.
> update webpack-dev-server version

- .github/workflows/deploy-pipeline.yml
- Gemfile
- Gemfile.lock
- config/database.yml
- docker-compose.yml
(don't merge - testing the pipelines)
> Set up initial pipeline using GitHub Actions

- app/controllers/application_controller.rb
- app/controllers/form_controller.rb
- app/views/form/display.html.erb
- config/routes.rb
Library is from: https://github.com/DFE-Digital/govuk-formbuilder
Route is temporary just to validate form components are displayed as expected.
> bring in rails gds form dependency

- package.json
- yarn.lock
Forced dependencies of dependencies with known security issues to not be outdated through use of package json resolutions.
> fix remaining dependabot alerts

- app/views/individual/check_answers.html.erb
> create check answer confirmation page

- app/mailers/gov_notify_mailer.rb
- docker-compose.yml
To be wired up when organisation form is finished
> Send organisation email method

- app/javascript/styles/application.scss
- app/javascript/styles/homes_for_ukraine.scss
- app/views/layouts/application.html.erb
Homes for Ukraine banner and override styles
> Add banner

- .github/workflows/deploy-pipeline.yml
Added template ids to secrets for consistency
> Add template ids to secrets for deployment pipeline

- app/controllers/individual_controller.rb
- app/controllers/organisation_controller.rb
- app/models/individual_expression_of_interest.rb
- app/models/organisation_expression_of_interest.rb
- app/views/individual/check_answers.html.erb
- app/views/individual/steps/1.html.erb
- app/views/individual/steps/11.html.erb
- app/views/individual/steps/12.html.erb
- app/views/individual/steps/2.html.erb
- app/views/individual/steps/3.html.erb
- app/views/individual/steps/7.html.erb
- app/views/organisation/check_answers.html.erb
- app/views/organisation/steps/1.html.erb
- app/views/organisation/steps/10.html.erb
- app/views/organisation/steps/14.html.erb
- config/locales/en.yml
- spec/models/individual_expression_of_interest_spec.rb
- spec/system/individual_eoi_spec.rb
- spec/system/organisation_eoi_spec.rb
> Ensure the data model is consistent

- app/controllers/individual_controller.rb
- app/controllers/organisation_controller.rb
- app/jobs/send_individual_update_job.rb
- app/jobs/send_organisation_update_job.rb
- app/use-cases/transfer_record.rb
And add method for updating an organisation & send organisation email
> Fix sidekiq error

- app/models/organisation_expression_of_interest.rb
- app/views/organisation/check_answers.html.erb
- app/views/organisation/steps/14.html.erb
Also corrected some check answers bits.
> Organisation privacy statement

- app/models/individual_expression_of_interest.rb
- app/models/organisation_expression_of_interest.rb
> Amend reference

- .gitignore
This PR simply adds `.vscode` (settings folder) to `.gitignore`
> Added .vscode to ignored folders

- app/controllers/concerns/routing_engine.rb
- app/controllers/unaccompanied_controller.rb
- app/models/unaccompanied_minor.rb
- app/views/sponsor-a-child/steps/28.html.erb
- app/views/sponsor-a-child/task_list.html.erb
- config/routes.rb
- spec/routing_engine_spec.rb
- spec/system/unaccompanied_minor_spec.rb
To add or remove over 16 year olds at the property
> Add names to list

- app/models/concerns/contact_details_validations.rb
- app/models/concerns/uam_validations.rb
- app/models/unaccompanied_minor.rb
- app/views/sponsor-a-child/steps/35.html.erb
- spec/models/unaccompanied_minor_spec.rb
- spec/system/unaccompanied_minor_spec.rb
Validations failing when submitted the application
> Fix validations

- app/views/sponsor-a-child/check_answers.html.erb
- spec/system/unaccompanied_minor_spec.rb
Handle dynamic application elements
> Render check answers

- app/models/unaccompanied_minor.rb
- spec/models/unaccompanied_minor_spec.rb
Enables the submission button for very basic cases. (Dynamic elements are not checked yet)
**To Follow**
Test and validate dynamic elements before enabling the functionality
> Enable application submit

- app/views/sponsor-a-child/steps/33.html.erb
https://digital.dclg.gov.uk/jira/browse/UKRSS-752
> Makes minor_contact_type exclusive if cannot be contacted is selected

- app/controllers/unaccompanied_controller.rb
- app/models/concerns/uam_validations.rb
- app/views/sponsor-a-child/steps/18.html.erb
- app/views/sponsor-a-child/steps/29.html.erb
- app/views/sponsor-a-child/steps/34.html.erb
https://digital.dclg.gov.uk/jira/browse/UKRSS-753
there is still one case where the validation looks a bit borked:
- if you fill day, month and use an invalid value (0 - 1899) for the year, it will show an error message in the year field and I can't get around it
> Use error summary for dates of birth (sponsor, child, adults)

- app/controllers/unaccompanied_controller.rb
> Add timeout to display action in UAM controller

- app/controllers/unaccompanied_controller.rb
- app/use-cases/transfer_record.rb
- spec/controllers/unaccompanied_controller_spec.rb
> Fail submissions dob

- app/models/unaccompanied_minor.rb
- spec/models/unaccompanied_minor_spec.rb
https://digital.dclg.gov.uk/jira/browse/UKRSS-785
Still in draft because the "Who will live there" section checks also need updating, plus I'm using this PR to run the full test suite
> 785 tasklist behaviour bug

- app/controllers/unaccompanied_controller.rb
- app/models/unaccompanied_minor.rb
- app/views/sponsor-a-child/task_list.html.erb
- spec/models/unaccompanied_minor_spec.rb
- spec/system/unaccompanied_minor_spec.rb
Jira ticket https://digital.dclg.gov.uk/jira/browse/UKRSS-773
> Resident details section not being included in the count of complete sections

- app/views/sponsor-a-child/steps/1.html.erb
- app/views/sponsor-a-child/steps/11.html.erb
- app/views/sponsor-a-child/steps/2.html.erb
- app/views/sponsor-a-child/steps/20.html.erb
- app/views/sponsor-a-child/steps/3.html.erb
- app/views/sponsor-a-child/steps/4.html.erb
- app/views/sponsor-a-child/steps/5.html.erb
- app/views/sponsor-a-child/steps/6.html.erb
- app/views/sponsor-a-child/steps/7.html.erb
Now on all pages, even if they need validation adding
> added error summaries to extra pages

- app/views/sponsor-a-child/task_list.html.erb
https://digital.dclg.gov.uk/jira/browse/UKRSS-818
See screenshot for how it looks now
> Correct the colour used when additional household members are marked as completed

- app/controllers/extract_document_controller.rb
- app/controllers/s3_bucket_controller.rb
- app/models/s3_object.rb
- app/services/storage_service.rb
- app/views/extract-document/list.erb
- config/routes.rb
This is very much a work in progress to start understanding the request & response from S3
> 500 s3 list

- .github/workflows/deploy-pipeline.yml
- app/services/foundry_service.rb
- spec/services/foundry_service_spec.rb
Call a new api endpoint in foundry to link uploaded files to applications
> 500 assign upload in foundry

- app/controllers/unaccompanied_controller.rb
- config/locales/en.yml
- spec/system/unaccompanied_minor_sponsor_other_names_spec.rb
Added validation to other sponsor name's choice page, now can't go past without picking an option
> 831 step 11 allows continue with no choice

- app/controllers/unaccompanied_controller.rb
- config/locales/en.yml
- spec/system/unaccompanied_minor_sponsor_other_nationalities_spec.rb
[JIRA# 831](https://digital.dclg.gov.uk/jira/browse/UKRSS-831)
Displays an error message if the user clicks continue **without** selecting yes or no.
> Show an error if no choice is made for extra nationalities

- app/controllers/unaccompanied_controller.rb
- app/helpers/application_helper.rb
- app/views/sponsor-a-child/steps/21.html.erb
- config/locales/en.yml
- spec/system/unaccompanied_minor_spec.rb
Jira ticket: https://digital.dclg.gov.uk/jira/browse/UKRSS-817
> Nationality dropdown default invalid value

- app/controllers/unaccompanied_controller.rb
- app/views/sponsor-a-child/steps/31.html.erb
- config/locales/en.yml
- spec/system/unaccompanied_minor_spec.rb
- spec/system/unaccompanied_minor_sponsor_other_adults_spec.rb
[JIRA# 841](https://digital.dclg.gov.uk/jira/browse/UKRSS-841)
This will validate entries of "other adults" id documents.
> 841 force selection on other adults documents

- config/locales/en.yml
Part of [JIRA 911](https://digital.dclg.gov.uk/jira/browse/UKRSS-911)
Change "what" to "which" in link text
> copy change what => which

- Gemfile.lock
- app/views/sponsor-a-child/guidance.html.erb
- app/views/sponsor-a-child/steps/10.html.erb
- app/views/sponsor-a-child/steps/12.html.erb
- app/views/sponsor-a-child/steps/13.html.erb
- app/views/sponsor-a-child/steps/16.html.erb
- app/views/sponsor-a-child/steps/22.html.erb
- app/views/sponsor-a-child/steps/24.html.erb
- app/views/sponsor-a-child/steps/25.html.erb
- app/views/sponsor-a-child/steps/27.html.erb
- app/views/sponsor-a-child/steps/28.html.erb
- app/views/sponsor-a-child/steps/31.html.erb
- app/views/sponsor-a-child/steps/32.html.erb
- app/views/sponsor-a-child/task_list.html.erb
- config/locales/en.yml
- spec/models/unaccompanied_minor_spec.rb
- spec/system/token_based_resume_controller_spec.rb
- spec/system/unaccompanied_minor_minors_details_spec.rb
- spec/system/unaccompanied_minor_other_adults_spec.rb
- spec/system/unaccompanied_minor_spec.rb
- spec/system/unaccompanied_minor_sponsor_other_adults_spec.rb
- spec/system/unaccompanied_minor_sponsor_other_names_spec.rb
- spec/system/unaccompanied_minor_sponsor_other_nationalities_spec.rb
Content update for [Jira-911] (https://digital.dclg.gov.uk/jira/browse/UKRSS-911)
> 911 big content update

- .github/workflows/deploy-pipeline.yml
- app/controllers/foundry_consent_upload_controller.rb
[JIRA-933](https://digital.dclg.gov.uk/jira/browse/UKRSS-933)
Secure consent uploader "admin" form behind basic auth.
Env vars are set and ready to go and entered into the password store.
> 933 - Secure consent uploader form behind basic auth

- .github/workflows/deploy-pipeline.yml
- app/controllers/foundry_consent_upload_controller.rb
BAsic auth requested across whole app, so reverting #273
> Emergency fix -revert by fixing forward

- .rubocop.yml
- app/controllers/application_controller.rb
As title - in response to our mini outage this morning!
> Simplify auth 'if' to explicitly check for staging

- app/controllers/unaccompanied_controller.rb
- spec/system/confirm_page_spec.rb
[Jira-760](https://digital.dclg.gov.uk/jira/browse/UKRSS-760)
Reference not showing in confirmation page if session times out and the page is reloaded. Now redirects back to "/sponsor-a-child/"
> 760 reference not showing

- spec/models/unaccompanied_minor_output_spec.rb
Jira ticket: https://digital.dclg.gov.uk/jira/browse/UKRSS-824
Quick comment: the point of this test is that, if at any point we do change one of the json attributes, it'll fail and the error will mention which field doesn't exist in the full attributes list.
This doesn't prevent anything from changing, but strengthens the team's awareness when things change
> Consolidate application json output

- app/controllers/unaccompanied_controller.rb
- app/helpers/application_helper.rb
- app/models/unaccompanied_minor.rb
- config/locales/en.yml
- spec/system/unaccompanied_minor_sponsor_other_nationalities_spec.rb
> Error if duplicated nationalities are added

- db/migrate/20220915161050_add_sponsor_email_confirmation.rb
- db/schema.rb
> :rotating_light: Add answers.email_confirm to all uam that have an email and no confirmation

- Dockerfile-dev
- Gemfile.lock
> Set bundler to version 2.3.22

- worker-manifest.yml
> Scale sidekick memory from 512m to 1G

- app/views/token-based-resume/select_multiple_applications.erb
> Apply proper class to fix alignment in table

- config/locales/en.yml
PR for [1003]( https://digital.dclg.gov.uk/jira/browse/UKRSS-1003 )
A Link on step 5 opens a new page when you click on it.
> adding target =blank to the a tag of sponsor_right_to_live_in_uk hint

- app/views/sponsor-a-child/steps/13.html.erb
Visually the same but changed for accessibility purposes. 
Ticket [1004](https://digital.dclg.gov.uk/jira/browse/UKRSS-1004)
> changed header on step 13 to be a h1

- app/views/sponsor-a-child/steps/24.html.erb
- config/locales/en.yml
PR for ticket [1013](https://digital.dclg.gov.uk/jira/browse/UKRSS-1013)
Changed step 24 text to be hint text. 
BEFORE:
AFTER:
> 1013 child address details

- app/controllers/unaccompanied_controller.rb
Jira: https://digital.dclg.gov.uk/jira/browse/UKRSS-1010
Sentry: https://sentry.io/organizations/dluhc-ulss/issues/3469337252/?project=6260319&query=is%3Aunresolved
> Ensures that we don't try to load adults when they are not present

- README.md
[Jira 992](https://digital.dclg.gov.uk/jira/browse/UKRSS-992)
This PR covers **documentation only** and **will not** need a production deployment.
- Add section to Readme covering monitoring and alerting
- Definition (out of repo) of a grafana graph and associated alert for low memory usage in Sidekiq. The alert is defined to trigger when average memory usage is less than 100000000 bytes for 15 minutes, indicating the Sidekiq instances are probably not running.
> 992 health and alerting

- app/services/storage_service.rb
- config/routes.rb
> Delete uncalled defunct s3 listing code

- app/views/sponsor-a-child/confirm.erb
PR for [1006](https://digital.dclg.gov.uk/jira/browse/UKRSS-1020)
Adding target = _blank to the links on the confirm page right at the end
> add target_blank to the confirm page links

- README.md
- bin/test.sh
- spec/rails_helper.rb
https://digital.dclg.gov.uk/jira/browse/UKRSS-964
Increases coverage to 84.26%. Further increases suffer from diminishing returns.
> Improve code coverage with explicit loading

- app/views/sponsor-a-child/steps/8.html.erb
Step 8 said NOT CURRENTLY USED and so we removed it. At the end of the eligibility flow so never actually reached and doesn't break the controller step process.
> removed step 8 for UAM as it was unused

- .github/workflows/deploy-pipeline.yml
[UKRSS-994](https://digital.dclg.gov.uk/jira/browse/UKRSS-994)
Will fail tests if test suite coverage falls below 83%. No minimum limit for individual files.
> 994: Include test coverage check in test step

- app/models/unaccompanied_minor.rb
Quick fix for LIVE sentry error : https://sentry.io/organizations/dluhc-ulss/issues/3640821048/?environment=production
> Fix nil error in live with nil guard

- app/views/additional-info/check_answers.html.erb
- app/views/individual/check_answers.html.erb
From https://sentry.io/organizations/dluhc-ulss/issues/3636440818/?environment=production&project=6260319
Ticket: [UKRSS-1068](https://digital.dclg.gov.uk/jira/browse/UKRSS-1068)
Added check for different_address existing (error is triggered when different_address is nil).
> 1068: Add check for different_address

- spec/system/sponsor_additional_details_spec.rb
- spec/system/unaccompanied_minor_sponsor_other_nationalities_spec.rb
> Spotted a few clean quick clean ups 😄 

- app/use-cases/transfer_record.rb
- spec/services/uam_transfer_record_spec.rb
- spec/support/unaccompanied_minor_helpers.rb
**Fourth and last pr** for [Jira ticket 991](https://digital.dclg.gov.uk/jira/browse/UKRSS-991)
This PR hooks in the output adapter to **post** filtered data to the foundry API
> 991 - Transfer record uses unaccompanied minor generate output to send to foundry

- app/views/sponsor-a-child/check_answers.html.erb
- spec/system/unaccompanied_minor_spec.rb
> Stop showing array brackets [] on check answers

- app/views/token-based-resume/save_return_resend_link.html.erb
> Aligns link with send link button

- app/controllers/eoi_controller.rb
Adding feature flag trap on eoi controller.
> adding feature flag trap

- spec/support/json_schema/expression_of_interest.json
[Jira ticket 1104](https://digital.dclg.gov.uk/jira/browse/UKRSS-1104)
First, and very basic, version of a JSON schema to define the payload that will be submitted to Palantir Foundry.
**TODO**
- Refine via end to end tests
> 1104 - First draft new EOI JSON schema

- app/controllers/eoi_controller.rb
- app/views/eoi/steps/can_you_commit.html.erb
- app/views/eoi/steps/now_we_need_your_info.erb
- config/routes.rb
Added "can you commit to hosting page" which is an extra step to self assessment flow and also now we need "your info" page which links to the start of the steps process.
> adding missing steps self assessment flow

- app/controllers/eoi_controller.rb
https://digital.dclg.gov.uk/jira/browse/UKRSS-1158
Validates to same rules as main address.
Validation performed in controlled as absence should not fail model validation (this step is optional)
> 1158: validation for different address

- app/views/eoi/confirm.erb
- app/views/eoi/steps/13.html.erb
- app/views/eoi/steps/16.html.erb
- app/views/eoi/steps/9.html.erb
- app/views/eoi/steps/challenges.html.erb
- app/views/eoi/steps/other_ways_to_help.html.erb
- config/locales/en.yml
- spec/support/eoi_helpers.rb
Content update for [ticket 1163](https://digital.dclg.gov.uk/jira/browse/UKRSS-1163), apart from bold radio labels on pets question
> Eoi content update

- app/javascript/packs/self_assessment_navigation.js
- app/views/eoi/steps/can_you_commit.html.erb
- app/views/eoi/steps/challenges.html.erb
- app/views/eoi/steps/is_your_property_suitable.html.erb
Adds validation for the self assessment flow.  
Works by adding the error class to the gov uk form thats necessary and also by changing the style of the actual error message text to display block.
> adding validation for self assessment

- app/views/index/index_eoi.html.erb
> removing back button on home page

- app/views/eoi/steps/can_you_commit.html.erb
- app/views/index/index_eoi.html.erb
> updating copy changes eoi

- app/controllers/concerns/eoi_workflow.rb
- app/controllers/eoi_controller.rb
- config/brakeman.ignore
Implements a state machine based workflow engine.
> 1183 navigation and workflow

- app/models/concerns/expression_of_interest_validations.rb
Original jira ticket: https://digital.dclg.gov.uk/jira/browse/UKRSS-1213
> Summary box date error bug

- app/models/concerns/expression_of_interest_validations.rb
- config/locales/en.yml
- spec/models/individual_expression_of_interest_spec.rb
Ticket https://digital.dclg.gov.uk/jira/browse/UKRSS-1216
Also ticket https://digital.dclg.gov.uk/jira/browse/UKRSS-1217
Also ticket https://digital.dclg.gov.uk/jira/browse/UKRSS-1219
This covers the entirety of https://digital.dclg.gov.uk/jira/browse/UKRSS-1215 (1218 has been marked as redundant and closed)
> Bedroom question bugs

- app/javascript/packs/self_assessment_navigation.js
- app/views/layouts/application.html.erb
Adding data attribute for cookies accepted and toggling checked states via JS
> adding data attribute for cookie accepted

- app/views/eoi/steps/other_ways_to_help.html.erb
- automated_tests/cypress/e2e/page_elements/EOI/eoi_elements.js
- config/locales/en.yml
PR for ticket [1260](https://digital.dclg.gov.uk/jira/browse/UKRSS-1260). Replaces lines that say open in a new page with opens in a new tab.
> Update language to use opens in a new tab

- app/views/index/index.html.erb
Content updates for the Home page - PR [1323](https://digital.dclg.gov.uk/jira/browse/UKRSS-1323)
> update content to for UAM homepage

- app/views/eoi/steps/can_you_commit.html.erb
- app/views/eoi/steps/challenges.html.erb
- app/views/eoi/steps/is_your_property_suitable.html.erb
Jira ticket: https://digital.dclg.gov.uk/jira/browse/UKRSS-1816
> [accessibility fixes] DAC Unlabelled Form Elements 01

- app/views/sponsor-a-child/steps/13.html.erb
- app/views/sponsor-a-child/steps/22.html.erb
- app/views/sponsor-a-child/steps/28.html.erb
@jrlord @GeorgianaNicolae what I have done here is add the `Action` table header, but as an alternative they suggest also using the description list. I tried it and it has a lot of repeated `Name` `Name` `Name` headers for instance so I think this is better in our case.
> DAC_Table_Header_01

- app/views/eoi/steps/privacy_statement.html.erb
- app/views/sponsor-a-child/steps/38.html.erb
- automated_tests/cypress/e2e/pages/EOI/eoi_backlink.js
- config/locales/en.yml
- spec/support/eoi_helpers.rb
- spec/support/unaccompanied_minor_helpers.rb
Replace duplicate content when confirming the reading of privacy statement.
> [accessibility fixes]  DAC_Headings_01 

- automated_tests/cypress/e2e/pages/EOI/eoi_backlink.js
- automated_tests/cypress/e2e/pages/EOI/eoi_e2e_hp.js
- automated_tests/cypress/e2e/pages/EOI/eoi_error_label.js
- automated_tests/cypress/e2e/pages/EOI/eoi_phone_number.js
- config/locales/en.yml
- spec/models/unaccompanied_minor_spec.rb
- spec/support/eoi_helpers.rb
- spec/system/eoi_validation_spec.rb
- spec/system/uam_sponsor_contact_details_spec.rb
- spec/system/unaccompanied_minor_child_contact_details_spec.rb
Add phone number format guidance
> [accessibility fixes] DAC_Error_Description_01

- app/views/sponsor-a-child/guidance.html.erb
- app/views/sponsor-a-child/task_list.html.erb
@jrlord these are the only two instances I found with the issue
> Update all page titles with wrong scope

- app/views/eoi/check_answers.html.erb
- app/views/eoi/steps/different_address.html.erb
- app/views/sponsor-a-child/confirm.erb
- config/locales/en.yml
Following review of staging a bunch of fixes were needed. A few missing 'opens in a new tab' warnings, and some broken translations.
> fix new tab warnings, broken translations

- app/models/concerns/uam_validations.rb
This helped
https://github.com/x-govuk/govuk-formbuilder/blob/main/lib/govuk_design_system_formbuilder/presenters/error_summary.rb#L5C13-L5C13
> [accessibility fixes] DAC_Error_Skip_Link_Order_Usability_01

- app/views/sponsor-a-child/steps/19.html.erb
- config/locales/en.yml
@GeorgianaNicolae @jrlord everything else *I believe* is in order
> [acessibility fixes] DAC_Labelling_Usability_01

- app/views/layouts/application.html.erb
Update: ran it past Gerrhon, he approves; asked to add the privacy statement and provided the link for it
> Consolidate footer

- app/views/eoi/steps/address.html.erb
- app/views/eoi/steps/email.html.erb
- app/views/eoi/steps/fullname.html.erb
- app/views/eoi/steps/hosting_start_date.html.erb
- app/views/eoi/steps/number_bedrooms.html.erb
- app/views/eoi/steps/number_people.html.erb
- app/views/eoi/steps/phone_number.html.erb
- app/views/eoi/steps/property_one_address.html.erb
- app/views/sponsor-a-child/steps/10.html.erb
- app/views/sponsor-a-child/steps/12.html.erb
- app/views/sponsor-a-child/steps/14.html.erb
- app/views/sponsor-a-child/steps/15.html.erb
- app/views/sponsor-a-child/steps/16.html.erb
- app/views/sponsor-a-child/steps/17.html.erb
- app/views/sponsor-a-child/steps/18.html.erb
- app/views/sponsor-a-child/steps/23.html.erb
- app/views/sponsor-a-child/steps/26.html.erb
- app/views/sponsor-a-child/steps/27.html.erb
- app/views/sponsor-a-child/steps/29.html.erb
- app/views/sponsor-a-child/steps/31.html.erb
- app/views/sponsor-a-child/steps/32.html.erb
- app/views/sponsor-a-child/steps/33.html.erb
- app/views/sponsor-a-child/steps/34.html.erb
- app/views/token-based-resume/save_return_resend_link.html.erb
- app/views/token-based-resume/session_resume_form.html.erb
> [accessibility fixes] DAC-Input-Type-Usability-01

- app/controllers/redirect_controller.rb
- config/routes.rb
- spec/controllers/redirect_controller_spec.rb
This PR changes the way we issue redirects, so that it's behind basic auth if needs be
> RedirectController with auth

- app/controllers/token_based_resume_controller.rb
- app/models/unaccompanied_minor.rb
- docker-compose.yml
- spec/controllers/token_based_resume_controller_spec.rb
- spec/models/unaccompanied_minor_spec.rb
- spec/system/token_based_resume_controller_spec.rb
Fix Sentry NoMethodError
Fix issue with full_name not being populated in db from application
Add tests for both
> Null fields
